name: hiking4nerds
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_map: any
  location:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/map/berlin/10/549/
    - assets/map/berlin/10/550/
    - assets/map/berlin/11/1098/
    - assets/map/berlin/11/1099/
    - assets/map/berlin/11/1100/
    - assets/map/berlin/11/1101/
    - assets/map/berlin/12/2196/
    - assets/map/berlin/12/2197/
    - assets/map/berlin/12/2198/
    - assets/map/berlin/12/2199/
    - assets/map/berlin/12/2200/
    - assets/map/berlin/12/2201/
    - assets/map/berlin/12/2202/
    - assets/map/berlin/13/4393/
    - assets/map/berlin/13/4394/
    - assets/map/berlin/13/4395/
    - assets/map/berlin/13/4396/
    - assets/map/berlin/13/4397/
    - assets/map/berlin/13/4398/
    - assets/map/berlin/13/4399/
    - assets/map/berlin/13/4400/
    - assets/map/berlin/13/4401/
    - assets/map/berlin/13/4402/
    - assets/map/berlin/13/4403/
    - assets/map/berlin/13/4404/
    - assets/map/berlin/13/4405/
    - assets/map/berlin/14/8786/
    - assets/map/berlin/14/8787/
    - assets/map/berlin/14/8788/
    - assets/map/berlin/14/8789/
    - assets/map/berlin/14/8790/
    - assets/map/berlin/14/8791/
    - assets/map/berlin/14/8792/
    - assets/map/berlin/14/8793/
    - assets/map/berlin/14/8794/
    - assets/map/berlin/14/8795/
    - assets/map/berlin/14/8796/
    - assets/map/berlin/14/8797/
    - assets/map/berlin/14/8798/
    - assets/map/berlin/14/8799/
    - assets/map/berlin/14/8800/
    - assets/map/berlin/14/8801/
    - assets/map/berlin/14/8802/
    - assets/map/berlin/14/8803/
    - assets/map/berlin/14/8804/
    - assets/map/berlin/14/8805/
    - assets/map/berlin/14/8806/
    - assets/map/berlin/14/8807/
    - assets/map/berlin/14/8808/
    - assets/map/berlin/14/8809/
    - assets/map/berlin/14/8810/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
